### ISSUE TITLE
Simple persistence implementation with embedded SQLite

### ISSUE THREAD

**Issue by paulodamaso** [paulodamaso/agamulator#44]
Add persistence implementation with embedded SQLite database. Add integration tests to database implementation.

**Comment by fabriciofx** [comment]
Why SQLite? Why not [H2](http://www.h2database.com/html/main.html)? It's totally wrote in Java and can be use as file, server and memory...

**Comment by paulodamaso** [comment]
@fabriciofx The only reason is that I've never user SQLite yet

**Comment by fabriciofx** [comment]
@paulodamaso So, do you want to use SQLite just to learn it?

**Comment by paulodamaso** [comment]
@fabriciofx Yes, basically

**Comment by fabriciofx** [comment]
@paulodamaso Ok. Thanks for your attention!

**Comment by paulodamaso** [comment]
@fabriciofx You're welcome!
