### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by paulodamaso** [paulodamaso/agamulator#7]
Tests are currently instantiating a lot of test objects; try to refactor them so they have just one assert (when possible). Try to remove qulice ignore tags when refactoring this code.

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#18](https://github.com/paulodamaso/agamulator/issues/18) is still not solved.

**Comment by 0pdd** [comment]
@paulodamaso the only puzzle [#18](https://github.com/paulodamaso/agamulator/issues/18) is solved here.
